[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "trading_app"
version = "2.0.0"
dependencies = [
"schwab-py==1.5.1",
"httpx",
"websockets>=16,<17",
"pykeepass",
"numpy",
"sounddevice"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

